const test = require("node:test");
const assert = require("node:assert/strict");
const {
  normalizeGuidedPathsInput
} = require("../../src/services/siteContentService");

test("normalizeGuidedPathsInput keeps assistant-created paths with slug-only titles", () => {
  const [path] = normalizeGuidedPathsInput([
    {
      slug: "late-night-identity",
      intro: "A saved path generated by the assistant.",
      postSlugs: ["what-i-dont-say-out-loud"]
    }
  ]);

  assert.equal(path.slug, "late-night-identity");
  assert.equal(path.title, "Late Night Identity");
  assert.deepEqual(path.postSlugs, ["what-i-dont-say-out-loud"]);
});
